<?php

/**
 * This file is part of Drunit
 *
 * (c) Korstiaan de Ridder <korstiaan@korstiaan.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

function drunit_test()
{
    return __FUNCTION__;
}

function drunit_test_init()
{
    drunit_test_static('init');    
}

function drunit_test_boot()
{
    drunit_test_static('boot');    
}

function drunit_test_static($val = null) 
{
    static $a = array();
    if (null !== $val) {
        $a[] = $val;
    }
    return $a;
}